package P_20211222.exception02;

import java.util.Scanner;

public class TryCatch01P353 {
	public static void main(String[] args) {
		int a,b;
		Scanner sc = new Scanner(System.in);
		a = sc.nextInt();
		b = sc.nextInt();
		try {
			
		}catch (ArithmeticException e) {
			// TODO: handle exception
		}
		System.out.println(a/b);
	}
}
