package P_20211222.exception02;

import java.util.Scanner;

public class TryCatch01P353 {
	public static void main(String[] args) {
		int a,b;
		Scanner sc = new Scanner(System.in);
		a = sc.nextInt();
		b = sc.nextInt();
		try {
			System.out.println(a/b);
		}catch (ArithmeticException e) {
			System.out.println("에러코드 : " + e);
		}catch(Exception e) {
			System.out.println("에러코드 : " + e.getMessage());
		}
	}
}
